# Documentation for SCSS Lint configuration
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

exclude: 'src/styles/fonts/**'

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 3

  PlaceholderInExtend:
    enabled: false

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%',                                     # Other
    ]
    properties: {}

  PropertySortOrder:
    enabled: true
    ignore_unspecified: true
    min_properties: 2
    separate_groups: false
    order:
      - 'content'
      - 'display'
      - 'align-content'
      - 'align-items'
      - 'align-self'
      - 'flex-direction'
      - 'flex-flow'
      - 'flex-grow'
      - 'flex-wrap'
      - 'justify-content'
      - 'vertical-align'
      - 'float'
      - 'position'
      - 'top'
      - 'right'
      - 'bottom'
      - 'left'
      - 'z-index'
      -
      - 'max-width'
      - 'max-height'
      - 'width'
      - 'height'
      - 'margin'
      - 'margin-top'
      - 'margin-right'
      - 'margin-bottom'
      - 'margin-left'
      - 'padding'
      - 'padding-top'
      - 'padding-right'
      - 'padding-bottom'
      - 'padding-left'
      - 'border'
      - 'border-top'
      - 'border-right'
      - 'border-bottom'
      - 'border-left'
      - 'overflow'
      -
      - 'background'
      - 'background-color'
      - 'background-image'
      - 'background-position'
      - 'background-repeat'
      - 'background-size'
      - 'box-shadow'
      - 'text-align'
      -
      - 'font'
      - 'font-family'
      - 'font-style'
      - 'font-size'
      - 'font-weight'
      - 'line-height'
      - 'letter-spacing'
      - 'color'
      - 'text-transform'
      - 'text-shadow'
      - 'white-space'
      -
      - 'opacity'

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: false
    convention: hyphenated_BEM # 'hyphenated_lowercase' or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
